// flow-typed signature: 030a0d51d7da2db8716b0c796bcd8992
// flow-typed version: <<STUB>>/react-router-enzyme-context_v1.2.0/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-enzyme-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-enzyme-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-enzyme-context/dist/react-router-enzyme-context.cjs' {
  declare module.exports: any;
}

declare module 'react-router-enzyme-context/dist/react-router-enzyme-context.esm' {
  declare module.exports: any;
}

declare module 'react-router-enzyme-context/rollup.config' {
  declare module.exports: any;
}

declare module 'react-router-enzyme-context/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-enzyme-context/dist/react-router-enzyme-context.cjs.js' {
  declare module.exports: $Exports<'react-router-enzyme-context/dist/react-router-enzyme-context.cjs'>;
}
declare module 'react-router-enzyme-context/dist/react-router-enzyme-context.esm.js' {
  declare module.exports: $Exports<'react-router-enzyme-context/dist/react-router-enzyme-context.esm'>;
}
declare module 'react-router-enzyme-context/rollup.config.js' {
  declare module.exports: $Exports<'react-router-enzyme-context/rollup.config'>;
}
declare module 'react-router-enzyme-context/src/index' {
  declare module.exports: $Exports<'react-router-enzyme-context/src'>;
}
declare module 'react-router-enzyme-context/src/index.js' {
  declare module.exports: $Exports<'react-router-enzyme-context/src'>;
}
