// flow-typed signature: ba35d02d668b0d0a3e04a63a6847974e
// flow-typed version: <<STUB>>/react-jss_v8.6.1/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-jss/dist/react-jss' {
  declare module.exports: any;
}

declare module 'react-jss/dist/react-jss.min' {
  declare module.exports: any;
}

declare module 'react-jss/lib/compose' {
  declare module.exports: any;
}

declare module 'react-jss/lib/compose.test' {
  declare module.exports: any;
}

declare module 'react-jss/lib/contextTypes' {
  declare module.exports: any;
}

declare module 'react-jss/lib/createHoc' {
  declare module.exports: any;
}

declare module 'react-jss/lib/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-jss/lib/index' {
  declare module.exports: any;
}

declare module 'react-jss/lib/index.test' {
  declare module.exports: any;
}

declare module 'react-jss/lib/injectSheet' {
  declare module.exports: any;
}

declare module 'react-jss/lib/injectSheet.test' {
  declare module.exports: any;
}

declare module 'react-jss/lib/jss' {
  declare module.exports: any;
}

declare module 'react-jss/lib/JssProvider' {
  declare module.exports: any;
}

declare module 'react-jss/lib/JssProvider.test' {
  declare module.exports: any;
}

declare module 'react-jss/lib/ns' {
  declare module.exports: any;
}

declare module 'react-jss/lib/propTypes' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-jss/dist/react-jss.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss'>;
}
declare module 'react-jss/dist/react-jss.min.js' {
  declare module.exports: $Exports<'react-jss/dist/react-jss.min'>;
}
declare module 'react-jss/lib/compose.js' {
  declare module.exports: $Exports<'react-jss/lib/compose'>;
}
declare module 'react-jss/lib/compose.test.js' {
  declare module.exports: $Exports<'react-jss/lib/compose.test'>;
}
declare module 'react-jss/lib/contextTypes.js' {
  declare module.exports: $Exports<'react-jss/lib/contextTypes'>;
}
declare module 'react-jss/lib/createHoc.js' {
  declare module.exports: $Exports<'react-jss/lib/createHoc'>;
}
declare module 'react-jss/lib/getDisplayName.js' {
  declare module.exports: $Exports<'react-jss/lib/getDisplayName'>;
}
declare module 'react-jss/lib/index.js' {
  declare module.exports: $Exports<'react-jss/lib/index'>;
}
declare module 'react-jss/lib/index.test.js' {
  declare module.exports: $Exports<'react-jss/lib/index.test'>;
}
declare module 'react-jss/lib/injectSheet.js' {
  declare module.exports: $Exports<'react-jss/lib/injectSheet'>;
}
declare module 'react-jss/lib/injectSheet.test.js' {
  declare module.exports: $Exports<'react-jss/lib/injectSheet.test'>;
}
declare module 'react-jss/lib/jss.js' {
  declare module.exports: $Exports<'react-jss/lib/jss'>;
}
declare module 'react-jss/lib/JssProvider.js' {
  declare module.exports: $Exports<'react-jss/lib/JssProvider'>;
}
declare module 'react-jss/lib/JssProvider.test.js' {
  declare module.exports: $Exports<'react-jss/lib/JssProvider.test'>;
}
declare module 'react-jss/lib/ns.js' {
  declare module.exports: $Exports<'react-jss/lib/ns'>;
}
declare module 'react-jss/lib/propTypes.js' {
  declare module.exports: $Exports<'react-jss/lib/propTypes'>;
}
