#
# Copyright (c) 2020 - present Cloudogu GmbH
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scm-manager.fullname" . }}
  labels:
    app: {{ include "scm-manager.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yml: |
    # base server config
    ##  Address to listen 0.0.0.0 means on every interface

    {{- if .Values.ingress.enabled -}}
    ## Evaluates headers set by a reverse proxy like X-Forwarded-For, X-Forwarded-Proto and X-Forwarded-Host
    forwardHeadersEnabled: true
    {{- end }}

    addressBinding: 0.0.0.0
    port: 8080
    contextPath: /scm

    ## increase http header size for mercurial
    httpHeaderSize: 16384

    # ssl config - ssl is only evaluated if key store path is set
    ## path to your cert file
    https:
      keyStorePath: ""
      keyStorePassword: secret
      keyStoreType: PKCS12
      sslPort: 8443
      redirectHttpToHttps: false

    tempDir: /var/cache/scm/work

    # logging
    log:
      rootLevel: WARN
      enableFileAppender: false
      enableConsoleAppender: true
      logger:
        sonia.scm: INFO
        com.cloudogu.scm: INFO

    webapp:
      ## Sets explicit working directory for internal processes, empty means default java temp dir
      workDir:
      ## Home directory "scm-home" which is also set for classpath
      homeDir: /var/lib/scm
      cache:
        dataFile:
          enabled: true
        store:
          enabled: true
      ## Warning: Enabling this option can lead to security issue.
      endlessJwt: false
      ## Number of async threads
      asyncThreads: 4
      ## Max seconds to abort async execution
      maxAsyncAbortSeconds: 60
      ## Amount of central work queue workers
      central-work-queue:
        workers: 4
      ## Strategy for the working copy pool implementation [sonia.scm.repository.work.NoneCachingWorkingCopyPool, sonia.scm.repository.work.SimpleCachingWorkingCopyPool]
      workingCopyPoolStrategy: sonia.scm.repository.work.SimpleCachingWorkingCopyPool
      ## Amount of "cached" working copies
      workingCopyPoolSize: 5
