// flow-typed signature: e87b860fca7047001bcde4b8780a8655
// flow-typed version: <<STUB>>/@scm-manager/ui-extensions_v0.1.2/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@scm-manager/ui-extensions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@scm-manager/ui-extensions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@scm-manager/ui-extensions/lib/binder' {
  declare module.exports: any;
}

declare module '@scm-manager/ui-extensions/lib/ExtensionPoint' {
  declare module.exports: any;
}

declare module '@scm-manager/ui-extensions/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@scm-manager/ui-extensions/lib/binder.js' {
  declare module.exports: $Exports<'@scm-manager/ui-extensions/lib/binder'>;
}
declare module '@scm-manager/ui-extensions/lib/ExtensionPoint.js' {
  declare module.exports: $Exports<'@scm-manager/ui-extensions/lib/ExtensionPoint'>;
}
declare module '@scm-manager/ui-extensions/lib/index' {
  declare module.exports: $Exports<'@scm-manager/ui-extensions/lib'>;
}
declare module '@scm-manager/ui-extensions/lib/index.js' {
  declare module.exports: $Exports<'@scm-manager/ui-extensions/lib'>;
}
