// flow-typed signature: 9be79ea52a669f6c266677d1d0bd3e9d
// flow-typed version: <<STUB>>/gitdiff-parser_v0.1.2/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gitdiff-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gitdiff-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gitdiff-parser/test/git.test' {
  declare module.exports: any;
}

declare module 'gitdiff-parser/test/hg' {
  declare module.exports: any;
}

declare module 'gitdiff-parser/test/hg.test' {
  declare module.exports: any;
}

declare module 'gitdiff-parser/test/perf-parse-diff' {
  declare module.exports: any;
}

declare module 'gitdiff-parser/test/perf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gitdiff-parser/index' {
  declare module.exports: $Exports<'gitdiff-parser'>;
}
declare module 'gitdiff-parser/index.js' {
  declare module.exports: $Exports<'gitdiff-parser'>;
}
declare module 'gitdiff-parser/test/git.test.js' {
  declare module.exports: $Exports<'gitdiff-parser/test/git.test'>;
}
declare module 'gitdiff-parser/test/hg.js' {
  declare module.exports: $Exports<'gitdiff-parser/test/hg'>;
}
declare module 'gitdiff-parser/test/hg.test.js' {
  declare module.exports: $Exports<'gitdiff-parser/test/hg.test'>;
}
declare module 'gitdiff-parser/test/perf-parse-diff.js' {
  declare module.exports: $Exports<'gitdiff-parser/test/perf-parse-diff'>;
}
declare module 'gitdiff-parser/test/perf.js' {
  declare module.exports: $Exports<'gitdiff-parser/test/perf'>;
}
