@startuml
Frontend -> SCM_REST_API: POST Request "create(BranchRequestDto)"
SCM_REST_API -> Repository_Service_Factory: create(Repository)
Repository_Service_Factory --> SCM_REST_API: Returns repository service
SCM_REST_API -> Repository_Branches_Command: getBranchesCommand()
Repository_Branches_Command --> SCM_REST_API: Returns branches command builder
SCM_REST_API -> Repository_Branches_Command: checkIfBranchDoesNotAlreadyExist()
SCM_REST_API -> Repository_Branch_Command: getBranchCommand()
Repository_Branch_Command --> SCM_REST_API: Returns branch command builder
SCM_REST_API -> Repository_Branch_Command_Builder: from(String parent)
SCM_REST_API -> Repository_Branch_Command_Builder: name(String branchName)
Repository_Branch_Command_Builder --> SCM_REST_API: Returns new branch
SCM_REST_API --> Frontend: Returns location of the new branch
@enduml
