// flow-typed signature: 35264e970923e4f3cda147e7c17e2407
// flow-typed version: <<STUB>>/react-diff-view_v1.8.1/flow_v0.109.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-diff-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-diff-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-diff-view/parse' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/CodeCell' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/Diff' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/Hunk' {
  declare module.exports: any;
}

declare module 'react-diff-view/src' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/parse' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/propTypes' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/selectors' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/SplitChange' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/SplitHunk' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/SplitWidget' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/UnifiedChange' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/UnifiedHunk' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/UnifiedWidget' {
  declare module.exports: any;
}

declare module 'react-diff-view/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-diff-view/index' {
  declare module.exports: $Exports<'react-diff-view'>;
}
declare module 'react-diff-view/index.js' {
  declare module.exports: $Exports<'react-diff-view'>;
}
declare module 'react-diff-view/parse.js' {
  declare module.exports: $Exports<'react-diff-view/parse'>;
}
declare module 'react-diff-view/src/CodeCell.js' {
  declare module.exports: $Exports<'react-diff-view/src/CodeCell'>;
}
declare module 'react-diff-view/src/Diff.js' {
  declare module.exports: $Exports<'react-diff-view/src/Diff'>;
}
declare module 'react-diff-view/src/Hunk.js' {
  declare module.exports: $Exports<'react-diff-view/src/Hunk'>;
}
declare module 'react-diff-view/src/index' {
  declare module.exports: $Exports<'react-diff-view/src'>;
}
declare module 'react-diff-view/src/index.js' {
  declare module.exports: $Exports<'react-diff-view/src'>;
}
declare module 'react-diff-view/src/parse.js' {
  declare module.exports: $Exports<'react-diff-view/src/parse'>;
}
declare module 'react-diff-view/src/propTypes.js' {
  declare module.exports: $Exports<'react-diff-view/src/propTypes'>;
}
declare module 'react-diff-view/src/selectors.js' {
  declare module.exports: $Exports<'react-diff-view/src/selectors'>;
}
declare module 'react-diff-view/src/SplitChange.js' {
  declare module.exports: $Exports<'react-diff-view/src/SplitChange'>;
}
declare module 'react-diff-view/src/SplitHunk.js' {
  declare module.exports: $Exports<'react-diff-view/src/SplitHunk'>;
}
declare module 'react-diff-view/src/SplitWidget.js' {
  declare module.exports: $Exports<'react-diff-view/src/SplitWidget'>;
}
declare module 'react-diff-view/src/UnifiedChange.js' {
  declare module.exports: $Exports<'react-diff-view/src/UnifiedChange'>;
}
declare module 'react-diff-view/src/UnifiedHunk.js' {
  declare module.exports: $Exports<'react-diff-view/src/UnifiedHunk'>;
}
declare module 'react-diff-view/src/UnifiedWidget.js' {
  declare module.exports: $Exports<'react-diff-view/src/UnifiedWidget'>;
}
declare module 'react-diff-view/src/utils.js' {
  declare module.exports: $Exports<'react-diff-view/src/utils'>;
}
